sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "123456"

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tGtf2rV77qDhsgzEtFL
    accessKeySecret: yn6TWUqEHLeRVPPEjnOSVwYVHxvFIt
    bucketName: cc-web-tails
  redis:
    port: 6379
    password: 123456
    host: localhost
    database: 0
  wechat:
    appid: wx4def69e821811987
    secret: f9f9eddc6252eba2baf73ea6ced6a8d5
    notifyurl: http://3e6a933c.r27.cpolar.top/notify/paysuccess