sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "123456"

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tGtf2rV77qDhsgzEtFL
    accessKeySecret: yn6TWUqEHLeRVPPEjnOSVwYVHxvFIt
    bucketName: cc-web-tails
  redis:
    port: 6379
    password: 123456
    host: localhost
    database: 0